name: tests-payments

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
    steps:
      - name: Create .env file
        run: |
          echo "STRIPE_KEY=${{ secrets.STRIP_KEY }}" >> .env
      - name: Debug env vars
        run: env
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
